### ISSUE TITLE
Future removal from Chrome Extension Store? 

### ISSUE THREAD

**Issue by eashman** [clvrobj/Pinboard-Plus#67]
I just noticed this today:

"This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions." shows up on the https://chromewebstore.google.com/detail/pinboard-plus/mphdppdgoagghpmmhodmfajjlloijnbd

Not sure what needs to change but I would be really sad if this stops working soon.  I use it a dozen times a day.  

Thoughts on what needs to change to fix this?

**Comment by clvrobj** [comment]
It's true that the extension will not be supported after a while. This is because Chrome is phasing out the manifest schema v2 that the extension uses, and transitioning to the new manifest V3. They're requiring all extensions to switch to the new version or they won't support them. However, it appears they won't stop supporting it immediately, so there's still some time left. More details can be found here: https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline. 
Unfortunately, due to changes in my personal life, I don't have enough time to maintain the extension and carry out the migration work. Therefore, you might want to consider finding another extension to use, there are some good ones in the Chrome app store. Alternatively, if any developer is willing to take on the migration work and submit a pull request, I should be able to review it, merge it, and publish the upgrade to the store.
